### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by baobabprince** [amnona/dbbact-calour#20]
I tried to use the REST-API but I didnt understand how to give it a parameter/query. 
```GET("http://api.dbbact.org/stats/stats")``` works fine. but

when I try to give parameters its fails, for example:
```
GET("http://api.dbbact.org/sequences/get_taxonomy_str?sequence=TAACTGTCAGTCTTGAGTACAGTAGAGGTGGGCGGAATTCGTGG")
```
can you supply example that works?

**Comment by amnona** [comment]
Cool idea.
Created an example notebook.
Since it is general to dbbact (and not specific to calour), put it in a new repo:
https://github.com/amnona/dbbact-examples

Let me know what functions you need example for :)
